Repository GSG-G13/Project-Postgres-SQL, pull requests merged in 2023-04, with the labels that each got.

#2 create file structure
  public/error/404.html
  public/error/500.html
  public/index.html
  public/index.js
  public/photographerPage/photographer.html
  public/photographerPage/style.css
  public/style.css
  server/app.js
  server/controllers/errors.js
  server/controllers/index.js
  server/database/db_build.js
  server/database/db_build.sql
  server/database/db_connection.js
  server/database/quires/getData.js
  server/database/quires/index.js
  server/database/quires/postData.js
  server/index.js
  server/router/index.js
Labels: done

#4 Create error file
  public/error/404.html
  public/error/500.html
Labels: done

#7 create user files front
  public/index.html
  public/index.js
  public/style.css
Labels: done

#18 create user table db
  server/database/db_build.sql
Labels: in-progress

#20 create table photogragher
  server/database/db_build.sql
Labels: waiting review

#23 file sc
  package-lock.json
  package.json
  server/app.js
  server/controllers/errors.js
  server/controllers/index.js
  server/index.js
  server/router/index.js
Labels: done

#28 create quires
  server/database/quires/index.js
  server/database/quires/postData.js
Labels: done

#29 create getdata
  .env
  server/database/quires/getData.js
Labels: done

#30 Most Project
  .env
  README.md
  public/index.html
  public/index.js
  public/photographerPage/index.js
  public/photographerPage/photographer.html
  public/photographerPage/style.css
  server/___test__/testing.test.js
  server/database/db_build.sql
  server/database/db_connection.js
  server/database/quires/getData.js
  server/database/quires/postData.js
  server/router/index.js
Labels: done

#32 update readme file
  README.md
Labels: done

#34 update some files
  public/index.html
  public/index.js
Labels: done
